---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[system_base::default]
      - recipe[system_base::locale]
      - recipe[system_base::rc_files]
    attributes:
      system_base:
        packages:
          - name: tree
          - name: psmisc
